### ISSUE TITLE
node-fetch dependency vulnerabilities

### ISSUE THREAD

**Issue by bigwoof91** [react-theming/storybook-addon#12]
Hi there! 👋 

Would it be possible to patch the `node-fetch` vulnerabilities and version a new release? It's just a low-severity denial of service warning... but a clean console is always nice! 😄 I can raise a PR if that helps? 

![image](https://user-images.githubusercontent.com/33911984/110745245-f4013080-8208-11eb-97d2-30509f51dcee.png)

**Comment by UsulPro** [comment]
Hey @bigwoof91 thanks for reporting
this fixed in v1.1.0
