### ISSUE TITLE
ReferenceError: htmlFontSize is not defined

### ISSUE THREAD

**Issue by bayuagpr** [react-theming/storybook-addon#18]
"@react-theming/storybook-addon": "^1.1.1"

I'm trying to use this addon with material UI

this how I use it:

preview.ts
```
import { withThemes } from "@react-theming/storybook-addon";
import { lightTheme, defaultTheme } from "../src/ThemeKnobs";
import { providerFn } from "./providerFn";

export const decorators = [
  withThemes(null, [lightTheme, defaultTheme], { providerFn: providerFn }),
];
```

providerFn.tsx
```
import { MuiThemeProvider, createMuiTheme } from "@material-ui/core/styles";

export const providerFn = ({ theme, children }) => {
  return <MuiThemeProvider theme={theme}>{children}</MuiThemeProvider>;
};
```

And I'm passing theme that already wrapped by createMuiTheme

but instead I got this following error in storybook:
```
ReferenceError: htmlFontSize is not defined
    at eval (eval at result (http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:192143:17), <anonymous>:1:43)
    at Object.pxToRem (http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:192144:18)
    at styles (http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:4782:34)
    at Object.create (http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:25938:35)
    at attach (http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:26378:32)
    at http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:26520:7
    at useSynchronousEffect (http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:26472:14)
    at useStyles (http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:26512:5)
    at WithStyles (http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:27004:21)
    at renderWithHooks (http://localhost:6007/vendors~main.a885dca276ee58d36a58.bundle.js:164060:18)
```

Also there is no difference result between using themeprovider from "@material-ui/core" and "@material-ui/core/styles"

and write it like this like in the docs is also produce the same result
```

  withThemes(null, [lightTheme, defaultTheme], { providerFn })

```

**Comment by ericreinheart** [comment]
same issue

**Comment by mregni** [comment]
Does someone know how to solve this problem?

I tried creating a preview-body.html with some styles (also tried it with preview-head.html, same result)
```
<style>
  html, body {
    font-size: 15px;
  }
</style>
```

And the style tags show up in the HTML but don't do anything, still the same error.

**Comment by lvandernoll** [comment]
What worked for me is passing a theme object that has not yet been wrapped by `createMuiTheme` to the `withThemes` function, and then wrapping it within the `providerFn`.

```js
const unWrappedTheme = {
  palette: {
    background: {
      default: '#fff',
    },
  },
};

const providerFn = ({ theme, children }) => {
  const wrappedTheme = createMuiTheme(theme);
  return (
      <ThemeProvider theme={wrappedTheme}>
          {children}
      </ThemeProvider>
  );
}

addDecorator(withThemes(null, [unWrappedTheme], { providerFn }));
```

**Comment by andreboyko** [comment]
I have same issue.
Looks like storybook-addon should not modify bundled to theme functions.

**Comment by UsulPro** [comment]
Solution of @lvandernoll is the correct one. Also this [example](https://github.com/react-theming/storybook-addon#using-with-material-ui) is same as shown in docs. The reason why we can pass wrapped themes is that Storybook renders components in isolated iframe and uses post message for passing objects. Functions are stripped away in this case
