### ISSUE TITLE
Registering addon in addons.js - Modules not found

### ISSUE THREAD

**Issue by KevinVandy** [react-theming/storybook-addon#2]
I don't know if I'm doing something wrong, but simply registering this addon in my addons.js file breaks my storybook build. I followed all of the other directions in the README but it doesn't matter since it cannot even register the addon.

Does this only support the newer storybook config way?

addons.js
`
import '@react-theming/storybook-addon/register';
`

ERROR in ./node_modules/@storybook/addon-devkit/dist/store/store.js
Module not found: Error: Can't resolve 'immutable' in 'C:\Users\username\Documents\formation-ui\node_modules\@storybook\addon-devkit\dist\store'
 @ ./node_modules/@storybook/addon-devkit/dist/store/store.js 18:17-37
 @ ./node_modules/@storybook/addon-devkit/dist/index.js
 @ ./node_modules/@react-theming/storybook-addon/dist/manager/register.js
 @ ./node_modules/@react-theming/storybook-addon/register.js
 @ ./.storybook/addons.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./.storybook/addons.js ./node_modules/@storybook/addon-docs/dist/register.js

ERROR in ./node_modules/@storybook/addon-devkit/dist/store/store.js
Module not found: Error: Can't resolve 'podda' in 'C:\Users\username\Documents\formation-ui\node_modules\@storybook\addon-devkit\dist\store'
 @ ./node_modules/@storybook/addon-devkit/dist/store/store.js 28:13-29
 @ ./node_modules/@storybook/addon-devkit/dist/index.js
 @ ./node_modules/@react-theming/storybook-addon/dist/manager/register.js
 @ ./node_modules/@react-theming/storybook-addon/register.js
 @ ./.storybook/addons.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./.storybook/addons.js ./node_modules/@storybook/addon-docs/dist/register.js

ERROR in ./node_modules/@storybook/addon-devkit/dist/store/store.js
Module not found: Error: Can't resolve 'react-komposer' in 'C:\Users\username\Documents\formation-ui\node_modules\@storybook\addon-devkit\dist\store'
 @ ./node_modules/@storybook/addon-devkit/dist/store/store.js 26:21-46
 @ ./node_modules/@storybook/addon-devkit/dist/index.js
 @ ./node_modules/@react-theming/storybook-addon/dist/manager/register.js
 @ ./node_modules/@react-theming/storybook-addon/register.js
 @ ./.storybook/addons.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./.storybook/addons.js ./node_modules/@storybook/addon-docs/dist/register.js

package.json
`
"peerDependencies": {
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
...
"devDependencies": {
  "@react-theming/storybook-addon": "^1.0.0",
...
  "@storybook/react": "^5.3.14",
...
`

**Comment by UsulPro** [comment]
Hi @KevinVandy Thanks for reporting!
Problem was on project's side with one of dependency. Now released `1.0.1` with locked up-to-date versions.

**Comment by UsulPro** [comment]
>Does this only support the newer storybook config way?

should support any way of configuring actually, it's handled by Storybook itself
