### ISSUE TITLE
Breaks background selection on canvas with @storybook/addon-essentials

### ISSUE THREAD

**Issue by Develliot** [react-theming/storybook-addon#21]
The strange thing with this bug is that background selection work fine with this addon in docs just not in canvas.

the backgrounds add on seems to style the div with the class 'sb-main-padded' this seems to be stuck with: 
background-color: #fffff
when using react-theming addon. 

I'm guessing under the hood they might be using theme provider decorators, no idea why docs is fine but canvas isn't.

**Comment by Develliot** [comment]
Ignore me, the reason why it work on docs is because this theme add on only works on the canvas, so there is going to be no clash with the background add on. I think it is a case of either or, not both. I'm closing this issue.

**Comment by maxsteenbergen-rh** [comment]
@Develliot Care to explain a bit further? I'm running into this issue as well but don't quite get what you're saying. Also, as soon as I add the decorator, the grid addon briefly flashes when trying to enable it. 
Note: I'm using styled-components though I don't think that's entirely related.

**Comment by Develliot** [comment]
So storybook has a mechanism for theming that you can apply using styled components theme or a plain object or what ever you choose to pass in as your theming object. 

The background selection addon uses this feature, so does this repo. So if two things are changing theme one of them has to win and one of them has to loose, I'm guessing the last one set up in the config file wins. So when I'm looking at the docs tab where this repo doesn't do anything changing backgrounds works. However in the canvas tab this repo does take effect essentially overriding any changes to the storybook theme so the backgrounds plug in can't.

That is at least what I think is happening.

**Comment by maxsteenbergen-rh** [comment]
That's very similar to what I'm seeing, but in my case the Docs tab doesn't work either.

**Comment by olejorgenb** [comment]
Yeah, something funky going on with the background. The `parameters.background.main/values` from main.js are completely ignored.
