### ISSUE TITLE
Only one theme is displaying at a time.

### ISSUE THREAD

**Issue by deh4g** [react-theming/storybook-addon#22]
Hi, greatly appreciate you creating this add-on.

I encountered a bug. As in, I have three themes in folder '../src/themes' and only one of my them is displaying. Any idea why that might be the case?

Here is the code I added to config.js:

> import { ThemeProvider } from '../src/index';
> import { withThemes } from '@react-theming/storybook-addon';
> import theme from '../src/theme'; **(There are 3 theme JS files in this folder.)**
> 
> const themingDecorator = withThemes(ThemeProvider, [theme]);
> addDecorator(themingDecorator);

Also, **when I click on the theme nothing changes**. May I know why that's the case? I believe I have followed your instructions properly.

Oh, I'm still using an older version of Storybook (version 5.2.6).

Kindly assist.
<img width="1220" alt="Screenshot 2021-06-23 at 11 01 26 AM" src="https://user-images.githubusercontent.com/44248956/123030591-9e4a4000-d415-11eb-9201-8a2eb8967122.png">

**Comment by UsulPro** [comment]
Hey @rodneysim 

>const themingDecorator = withThemes(ThemeProvider, [theme]);

here you need to pass an array with themes

something like

```
const themingDecorator = withThemes(ThemeProvider, [theme1, theme2, theme3]);
```

I see you have a default export from ../src/theme probably you need to export all of them:

```
import {theme1, theme2, theme3} from '../src/theme';
```

depending on how is your theme.js looking
