### ISSUE TITLE
Story keeps remounting when changes to controls are made

### ISSUE THREAD

**Issue by wahidshafique** [react-theming/storybook-addon#27]
Using a standard theming decorator like this
```
export const decorators = [Story => <ThemeProvider>{Story()}</ThemeProvider>];
```
gives me this https://gyazo.com/a421d82700afba97fa9a0b6b66e72612

However, using the recommended approach

```
const themingDecorator = withThemes(ThemeProvider, [theme]);
export const decorators = [themingDecorator];
```

causes the component to continually remount whenever a change to the controls is made

https://gyazo.com/032167887ca9c9d872a1ef19aaa20896

**Comment by victor-grajski** [comment]
+1 to this. My Storybook uses Material UI and Typescript, and I'm able to successfully toggle between themes, however, whenever I change something on the control panel, the theme always resets to the first one in the list.

**Comment by laytong** [comment]
it also happens for me using `addDecorator`

**Comment by ShadyF** [comment]
Any updates on this? I'm facing this as well and can't seem to find a solution.

**Comment by imgdiegoleal** [comment]
+1

**Comment by RHeynsZa** [comment]
Just have a look at https://github.com/react-theming/storybook-addon/issues/39#issuecomment-1020989596

This nullifies the use of this addon
