### ISSUE TITLE
Material UI v5.0 Theme is not applied

### ISSUE THREAD

**Issue by Boimb** [react-theming/storybook-addon#30]
Hi,
I'm trying to use this addon with React Material-UI v5.0 (currently next)
I've configured all my storybook as mentioned in the doc but the template seems not to be applied.
I know v5 is not the current stable, and has breaking changes (location of Theme related functions) with the current version but it seemed to me that it could be working if I imported them well.

Here's what I did:

```javascript
// main.js
 "addons": [
    "@react-theming/storybook-addon",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app"
  ]

// preview.js
import { ThemeProvider, createTheme } from '@material-ui/core';
import { addDecorator } from '@storybook/react';
import { withThemes } from '@react-theming/storybook-addon';
import { red } from '@material-ui/core/colors';

const theme = {
  palette: {
    primary: {
      main: red[50],
    }
  }
}

const providerFn = ({ theme, children }) => {
  const muTheme = createTheme(theme);
  return <ThemeProvider theme={muTheme}>{children}</ThemeProvider>;
};
// pass ThemeProvider and array of your themes to decorator
addDecorator(withThemes(null, [theme], { providerFn }));

// Button.stories.tsx
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Button } from '@material-ui/core';

export default {
  title: 'Example/Button',
  component: Button,
  argTypes: {
    color: {
      options: ['primary', 'secondary'],
      control: { type: 'radio' }
    }
  }
} as ComponentMeta<typeof Button>;

const Template: ComponentStory<typeof Button> = (args) => (
  <Button {...args}>
    Button
  </Button>
);

export const Primary = Template.bind({});
Primary.args = {
  color: 'primary',
  variant: 'contained'
};

```

And inside Storybook, the Button is showing the classic Blue from default Theme.

I'm using TS, could this be the issue ? Or maybe I missed something else?
Thx for your support.

Nota: If this can help, I have an error in the console, meaning, everything did not go well:

> Warning: React does not recognize the `originalStoryFn` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalstoryfn` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at MuiButtonBase-root
    at ButtonBase (http://localhost:5006/vendors~main.iframe.bundle.js:4928:94)

**Comment by Boimb** [comment]
Hum... Seems I did too much changes on my code without reloading the server. 
All that I described just above happens only when the addon is not activated and the ThemeProvider is added inside the story, on the template.
Sorry for this bad ticket.

Nevertheless, it seems that it's not working at all with the addon activated like I described on my previous comment.

**Comment by UsulPro** [comment]
Hey @Boimb thanks for reporting this. I'll check it this week later. Sorry no free time at all

**Comment by cshamrick** [comment]
@Boimb I ran into the same issue until I realized it's addressed in Material UI v5.0's [v4 migration guide](https://next.material-ui.com/guides/migration-v4/#storybook-emotion-with-v5) as well as in [this issue](https://github.com/mui-org/material-ui/issues/24282#issuecomment-796755133):

> If your project use Storybook v6.x, you will need to update .storybook/main.js webpack config to use the most recent version of emotion.
> 
> ```js
> // .storybook/main.js
> 
> const path = require('path');
> const toPath = (filePath) => path.join(process.cwd(), filePath);
> 
> module.exports = {
>   webpackFinal: async (config) => {
>     return {
>       ...config,
>       resolve: {
>         ...config.resolve,
>         alias: {
>           ...config.resolve.alias,
>           '@emotion/core': toPath('node_modules/@emotion/react'),
>           'emotion-theming': toPath('node_modules/@emotion/react'),
>         },
>       },
>     };
>   },
> };
> ```

I hope that helps!

**Comment by Boimb** [comment]
@cshamrick Thx a looot!
Had my theme applied to the stories if I "manually add the ThemeProvider" on each of them.
Have to dig a little bit more if I can have a decorator to make it wrap all my stories and avoid import it manually.
Ofc, if you managed to do it, I'd really appreciate your insights once again :D

**Comment by cshamrick** [comment]
@Boimb sure - my project is a Gatsby site, so storybook was added per Gatsby's [official guide](https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/). All of the Gatsby-specific configuration is explained in the comments. I don't think they are relevant to your issue, but I included them in case they turn out to be significant. Definitely omit those sections if they aren't needed for your project. Here's my setup:

Add Storybook with Webpack 5 support to the project:
```
npx -p @storybook/cli sb init
yarn add -D @storybook/builder-webpack5 @storybook/manager-webpack5
```

Configure Storybook with Webpack 5, `@react-theming/storybook-addon`, and `emotion`:
```js
// .storybook/main.js

const path = require("path");
const toPath = (filePath) => path.join(process.cwd(), filePath);

module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@react-theming/storybook-addon",
  ],
  core: {
    builder: "webpack5",
  },
  webpackFinal: async (config) => {

    // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
    config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/];

    // use babel-plugin-remove-graphql-queries to remove static queries from components when rendering in storybook
    config.module.rules[0].use[0].options.plugins.push(
      require.resolve("babel-plugin-remove-graphql-queries")
    );

    // required for Material UI v5 - see https://next.material-ui.com/guides/migration-v4/#storybook-emotion-with-v5
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          "@emotion/core": toPath("node_modules/@emotion/react"),
          "emotion-theming": toPath("node_modules/@emotion/react"),
        },
      },
    };
  },
};
```

`.storybook/preview.js`:
```js
import { action } from "@storybook/addon-actions";
import { ThemeProvider, createTheme } from "@material-ui/core/styles";
import { withThemes } from "@react-theming/storybook-addon";

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};

// Gatsby's Link overrides:
// Gatsby Link calls the `enqueue` & `hovering` methods on the global variable ___loader.
// This global object isn't set in storybook context, requiring you to override it to empty functions (no-op),
// so Gatsby Link doesn't throw any errors.
global.___loader = {
  enqueue: () => {},
  hovering: () => {},
};

// This global variable is prevents the "__BASE_PATH__ is not defined" error inside Storybook.
global.__BASE_PATH__ = "/";

// Navigating through a gatsby app using gatsby-link or any other gatsby component will use the `___navigate` method.
// In Storybook it makes more sense to log an action than doing an actual navigate. Checkout the actions addon docs for more info: https://github.com/storybookjs/storybook/tree/master/addons/actions.

window.___navigate = (pathname) => {
  action("NavigateTo:")(pathname);
};

const dark = createTheme({
  palette: {
    mode: "dark"
  }
});

const light = createTheme({
  palette: {
    mode: "light"
  }
});

const providerFn = ({ theme, children }) => {
  // this fixes broken theme functions
  const serialTheme = JSON.parse(JSON.stringify(theme));
  const muiTheme = createTheme(serialTheme);
  return <ThemeProvider theme={muiTheme}>{children}</ThemeProvider>;
};

// set Storybook's background to the theme's default
const onThemeSwitch = (context) => {
  const { theme } = context;
  const background = theme.palette.background.default;
  const parameters = {
    backgrounds: {
      default: background,
    },
  };
  return {
    parameters,
  };
};

const themingDecorator = withThemes(null, [dark, light], {
  providerFn,
  onThemeSwitch,
});

export const decorators = [themingDecorator];
```

**Comment by Boimb** [comment]
@cshamrick thanks for this! ❤️ 
Still struggling having the decorator OK.

If I make my own decorator like this:
```javascript
//.storybook/decorators.js
import { ThemeProvider } from '@material-ui/core';
import { theme } from '../src/styles/theme';

export const themeDecorator = (Story) => <ThemeProvider theme={theme}>
  <Story />
</ThemeProvider>
```

and in my story:
```javascript
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Button } from '@material-ui/core';
import { themeDecorator } from '../../.storybook/decorators';

export default {
  title: 'Example/Button',
  component: Button,
  decorators: [
    themeDecorator // My own decorator
  ],
  argTypes: {
    color: {
      type: 'inline-radio',
      options: ['primary', 'secondary', 'success', 'error', 'info', 'warning']
    }
  }
} as ComponentMeta<typeof Button>;

const Template: ComponentStory<typeof Button> = (args) => {
  return <Button {...args}>
    Button
  </Button>
}

export const Contained = Template.bind({});
Contained.args = {
  color: 'primary',
  variant: 'contained'
};

```
It works like a charm.
But if I do not import and add it to the decorators array , I got an error saying `values is not defined` inside the storyboook canvas, and `Warning: React does not recognize the 'originalStoryFn' prop on a DOM element`

I should not have to add it right ? That's the meaning of the "addDecorator" in preview.js.

Here are my conf files: 

```javascript
//main.js
const path = require('path');
const toPath = (filePath) => path.join(process.cwd(), filePath);

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@react-theming/storybook-addon",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app"
  ],
  "webpackFinal": async (config) => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          '@emotion/core': toPath('node_modules/@emotion/react'),
          'emotion-theming': toPath('node_modules/@emotion/react'),
        },
      },
    };
  },
}

```
```javascript
//preview.js
import { ThemeProvider } from '@material-ui/core';
import { addDecorator } from '@storybook/react';
import { withThemes } from '@react-theming/storybook-addon';
import { theme } from '../src/styles/theme'; // This theme is done using the createTheme() from @material-ui/core
import '../src/styles/common.scss';

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}

const providerFn = ({ theme, children }) => {
  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
};
addDecorator(withThemes(null, [theme], { providerFn }));
```
I'm not using webpack 5, but it doesn't seem to be the issue there, and all the rest seems to be the same as you (except for Gatsby things)
Once again, thanks for your help, you definitely made me move forward!

**Comment by cshamrick** [comment]
@Boimb change this:
```js
const providerFn = ({ theme, children }) => {
  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
};
```

to this:
```js
import { ThemeProvider, createTheme } from "@material-ui/core/styles";

const providerFn = ({ theme, children }) => {
  // this fixes broken theme functions
  const serialTheme = JSON.parse(JSON.stringify(theme));
  const muiTheme = createTheme(serialTheme);
  return <ThemeProvider theme={muiTheme}>{children}</ThemeProvider>;
};
```

**Comment by olejorgenb** [comment]
I got the `values is not defined` error using material-ui 4.x (4.11). cshmaricks workaround resolved it.

**Comment by UsulPro** [comment]
Hey guys! It looks like the example in the last @barhantas response solves this issue! Let me know if there is anything that should be done on this addon side.
