### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by danwoods** [react-theming/storybook-addon#56]
Hello, I tried to install via `npm i --save-dev @react-theming/storybook-addon` and I get the following error

<img width="745" alt="Screen Shot 2022-03-28 at 3 42 03 PM" src="https://user-images.githubusercontent.com/145783/160492236-9616c679-354d-4728-b649-4f03e00a0dd9.png">

It looks like some progress has been made towards this issue (https://github.com/react-theming/storybook-addon/issues/14), so I thought maybe the fixes hadn't been published, so I tried `npm i react-theming/storybook-addon` to install from master, but I get the same error.

How can I install this?

**Comment by AlexandrLitkevich** [comment]
Good afternoon, thank you for contacting us.This is an emotion problem, currently in the process of being solved.

**Comment by danwoods** [comment]
Has this been solved?

**Comment by rociodiaz-sistemas** [comment]
Is there any hope this will get fixed?

**Comment by AlexandrLitkevich** [comment]
Hi I will be looking for a solution next week
