### ISSUE TITLE
Chromatic support?

### ISSUE THREAD

**Issue by matthew-dean** [react-theming/storybook-addon#61]
~Using this library / tool, how would we auto-switch snapshots for Chromatic to take a snapshot per story per theme?~

Note, after a _lot_ of debugging with the Chromatic team, and build snapshots failing over and over, we narrowed it down to this particular library. Note that this fails Chromatic builds / verification! I don't know why, and they couldn't produce errors that explained it.

**Comment by usulpro** [comment]
@matthew-dean could you share what exactly falls?
Probably we need to add a current theme to the URL so you can open a specific theme. Now it's not supported
