### ISSUE TITLE
Support react 18

### ISSUE THREAD

**Issue by Averethel** [react-theming/storybook-addon#62]
Hello, we use the addon in storybook with chakra-ui. 
In their most recent release, they switched to react 18. 

Would it be possible to relax the peer dependency requirements on react version or does it require some more work on the addon internals?
I'd be happy to support here if it's more complex than just adding another version to peer deps too.

**Comment by j51217123** [comment]
@Averethel @usulpro 
I’ am not very good at English, so please bear with me.

Hello, I use React 18.0.0 and storybook v6.5.0 in my side-project, but the latest version isn't supported.
I want to know when I can install this package with the new version, thanks 

![image](https://user-images.githubusercontent.com/65345958/169447326-2dbe491c-095d-452d-b515-a9564308c3db.png)

**Comment by usulpro** [comment]
Hi @j51217123 we will release the latest version today
