### ISSUE TITLE
Change background color with the theme

### ISSUE THREAD

**Issue by edulix** [react-theming/storybook-addon#7]
It should be automatic that depending on the theme, it's easy to set the background color of the story. Currently the only way I've found is adding a div wrapper in the providerFn, but it's a limited solution because it shows some  ugly unthemed borders.

**Comment by UsulPro** [comment]
Hey @edulix 

This addon intends to manage components theme but not Storybook itselfs. Usually you don't want to keep storybook background in your app's theme? But I understand your needs. 
  
Storybook has an API for managing own theme
https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart

Also there is a background addon for changing preview area color
https://storybook.js.org/docs/react/essentials/backgrounds

Will this work for you?

**Comment by edulix** [comment]
For now I'm using just the backgrounds addon. I'm not sure I follow your logic. I don't want to keep storybook background i my app's theme. I'm trying to easily change the theme of the app and see the widget in a context similar to the one it will be used on. 

So for example if I'm doing a component with some paragraphs of text, it makes sense to try the component with the dark theme and see how it responds. But it makes sense that in the dark theme the text will be whitish, so if the background is not changed it will be unreadable. I think it pretty much makes sense to, at least optionally, be able to link the background color of the story together with the theme.

**Comment by UsulPro** [comment]
Thanks Eduardo :)

Yes I really understand this inconvenience. I've faced this as well. Currently we don't have any way to switch Storybook theme or integrate with background addon. Maybe it's worth to add such option :thinking: 

For a while why wrapping into a custom div doesn't work for you? It's common to wrap components with some providers in general. You could have a single global decorator for that. What do you think?

**Comment by edulix** [comment]
To be honest, I don't want to have a half-baked visual result, that's why I prefer not using a div wrapper that looks bad and makes the visual result of a widget confusing because it doesn't change the whole background, leaving some borders in other colors.

What I've seen other plugin do is to directly change the CSS style of the iframe:
https://github.com/semoal/themeprovider-storybook/blob/master/src/Themes.tsx#L69

But that cannot be done within the providerFn because it's being executed within the iframe and no on the top frame. I also looked at the backgrounds addon (see https://github.com/storybookjs/storybook/blob/next/addons/backgrounds/src/containers/BackgroundSelector.tsx#L100 ) and tried to use the `useGlobals` hook inside the `providerFn` to change the background color, but the same thing happens. You cannot call that within the iframe. So the solution must happen outside the `providerFn`, but I haven't explored how..

**Comment by ggascoigne** [comment]
A bit of poking around and I might have a simpler fix.

I'm using material ui, I have my two themes imported and I set parameters to include:

```js
  backgrounds: {
    default: lightThemeOptions.themeName,
    values: [
      {
        name: darkThemeOptions.themeName,
        value: darkThemeOptions.palette.background.default,
      },
      {
        name: lightThemeOptions.themeName,
        value: lightThemeOptions.palette.background.default,
      },
    ],
  },
```

then I changed https://github.com/react-theming/storybook-addon/blob/master/src/preview/onThemeSwitch.js#L40 to simply set the default background to the theme name and not a color.  

```js
  const parameters = {
    backgrounds: {
      default: theme.name
    }
  };
```


It's a hack right now, but I'll probably use patch-package to try it longer term.

Whenever I change the theme, the default background changes in sync with it.

**Comment by UsulPro** [comment]
Now this can be achieved via `onThemeSwitch` option
