### ISSUE TITLE
Using with MantineJS

### ISSUE THREAD

**Issue by emilybuc** [react-theming/storybook-addon#71]
Hi! 
I found your plugin for storybook and I think it looks perfect for what I'm building, 
Only issue is that I'm using MantineJS for my styling and i dont seem to be able to get it to work.
Im unsure if it currently supports MantineJS?
Thank you

**Comment by usulpro** [comment]
Hey @emilybuc 

This addon should work fine with any library having a theme provider. To make it work you'd need to pass your custom `providerFn` function into `withThemes(null, [theme], { providerFn });` 

This could look somehow like this:

```js
import { MantineProvider } from '@mantine/core';

const providerFn = ({ theme, children }) => {
  return <MantineProvider theme={theme}>{children}</MantineProvider>;
};

```

Let me know if you still have any issues with it
