### ISSUE TITLE
Theme switches when I switch component variant

### ISSUE THREAD

**Issue by zementeshome** [react-theming/storybook-addon#72]
Hi there,

I'm running into an issue with the theme switching whenever I click on a different variant. I have primary, secondary and tertiary variants for my button component. For example, when I select a different theme and click on secondary, it ends up selecting the first theme in the array and applies the styles for the secondary button for that theme. 

I noticed in your demo when I select Light Theme 2, I'm able to click on Buttons 1, 2 and 3 and see the theme apply to all the variants and it stays on the selected theme. 

Attached is a gif.

![2022-07-18 14 34 10](https://user-images.githubusercontent.com/62260287/179579617-4419587b-1209-4f02-b014-bb84e84cbe9c.gif)

**Comment by zementeshome** [comment]
@usulpro any help would be greatly appreciated!

**Comment by usulpro** [comment]
@zementeshome thanks for reporting this. Indeed the theme should persist. It looks like we have a bug here

**Comment by usulpro** [comment]
@zementeshome 
we released a [1.1.7](https://www.npmjs.com/package/@react-theming/storybook-addon/v/1.1.7) with hotfix

**Comment by zementeshome** [comment]
@usulpro yay, working now! thank you.

**Comment by Evgeny-Timoshin-R3** [comment]
@usulpro I am experiencing the same behaviour in 1.1.10. With Material UI, is the bug back?

**Comment by zementeshome** [comment]
@Evgeny-Timoshin-R3 @usulpro i'm also experiencing this bug again in 1.1.10 and we're using chakra. thanks for calling this out!
