### ISSUE TITLE
getColorSnippet is undefined in v1.1.8

### ISSUE THREAD

**Issue by sdaconceicao** [react-theming/storybook-addon#76]
CI tests are currently failing with the same issue. I'm seeing this error after updating to 1.1.8

vendors~main.manager.bundle.js:31908 Uncaught ReferenceError: getColorSnippet is not defined

**Comment by usulpro** [comment]
Hi @sdaconceicao thanks for reporting this
Please switch to 1.1.9 where it's fixed
