### ISSUE TITLE
Uncaught ReferenceError: colorSnippet is not defined

### ISSUE THREAD

**Issue by zementeshome** [react-theming/storybook-addon#77]
Hi there,

I just recently upgraded to 1.1.9 and i'm getting this error when I try to edit values in the object. Didn't get this error in 1.1.7.

![2022-11-29 15 18 47](https://user-images.githubusercontent.com/62260287/204639244-f25eebe7-bcd3-45ea-aeb6-5b4c0b1d31d9.gif)

![Screen Shot 2022-11-29 at 3 19 46 PM](https://user-images.githubusercontent.com/62260287/204639363-2134387a-20de-4322-a092-00f485217f22.png)

![Screen Shot 2022-11-30 at 11 53 10 AM](https://user-images.githubusercontent.com/62260287/204859408-b8d1b8b4-2d85-4348-a506-9f277587298f.png)

@usulpro any help would be greatly appreciated!

**Comment by CosminDinu12** [comment]
Same error here

**Comment by usulpro** [comment]
Thanks guys for reporting this!
fixed in 1.1.10 :)
