### ISSUE TITLE
Storybook's "dark" theme support

### ISSUE THREAD

**Issue by agurtovoy** [react-theming/storybook-addon#8]
Hi there,

First of all, thanks for the nice addon! I'm using Storybook's built-in ["dark" theme](https://storybook.js.org/docs/react/configure/theming#global-theming), and it looks like the addon doesn't fully support it:

<img width="1223" alt="Screen Shot 2021-01-24 at 4 54 13 PM" src="https://user-images.githubusercontent.com/3394202/105646307-d3e9fd80-5e64-11eb-8176-d0315967a75c.png">

```JS
// .storybook/manager.js

import { addons } from "@storybook/addons";
import { themes } from "@storybook/theming";

addons.setConfig({
    theme: themes.dark,
});
```

Please let me know if you'd prefer a PR instead of a bug submit :)

**Comment by UsulPro** [comment]
Hey @agurtovoy
Thank you for reporting this. PRs are always welcome also!

**Comment by UsulPro** [comment]
closing as it was fixed already
