### ISSUE TITLE
Support for Storybook v7

### ISSUE THREAD

**Issue by JulioC** [react-theming/storybook-addon#86]
Storybook v7 is [in beta](https://storybook.js.org/blog/7-0-beta/) for a while now, and looks like this addon doesn't support it yet.

---

From my tests, it appears that a [change in the default export of  `@storybook/addons` ](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-more-default-export-from-storybookaddons) is affecting `@storybook/addon-devkit` which is used by `@react-theming/storybook-addon`.

Since addon-devkit has not been updated in a couple of years, it would be nice to follow their recommendation and migrate to `@storybook/addon-kit`, which already supports v7.

**Comment by JulioC** [comment]
Since we have no updates on this fix, I've used [patch-package](https://www.npmjs.com/package/patch-package) to workaround the issue on my projects. The patch file 'patches/@storybook+addon-devkit+1.4.2.patch' shown below.

```diff
diff --git a/node_modules/@storybook/addon-devkit/dist/ChannelStore.js b/node_modules/@storybook/addon-devkit/dist/ChannelStore.js
index 5e4ee9d..14dd945 100644
--- a/node_modules/@storybook/addon-devkit/dist/ChannelStore.js
+++ b/node_modules/@storybook/addon-devkit/dist/ChannelStore.js
@@ -31,7 +31,7 @@ class ChannelStore {
 
     _defineProperty(this, "onConnectedFn", () => {});
 
-    _defineProperty(this, "channel", _addons.default.getChannel());
+    _defineProperty(this, "channel", _addons.default.addons.getChannel());
 
     _defineProperty(this, "connect", () => {
       if (this.isPanel) {

```

**Comment by swrobel** [comment]
Thanks for the workaround! Unforunately, SB7 compatibility seems a bit more complicated. I'm seeing crashes on docspages for any templates that receive props when using this addon with Storybook 7.0.0-rc.7. It's something this simple that triggers it:

```jsx
const Template = ({ variant }) => <Button variant={variant}>Default</Button>
```

With this addon:
<img width="795" alt="Screenshot 2023-03-23 at 9 03 46 AM" src="https://user-images.githubusercontent.com/157270/227395957-3612898d-20b5-47e0-ac11-bfbc7df2f85e.png">

Without:
<img width="1413" alt="Screenshot 2023-03-23 at 5 43 48 PM" src="https://user-images.githubusercontent.com/157270/227396013-e8eab79c-c5f4-44d2-9a71-dd85b16e165b.png">

**Comment by thisislawatts** [comment]
In case this is helpful for anyone else, I ended up ejecting `@react-theming/storybook-addon` in favour of adding a _Theme_ toggle directly into Storybook v7.

```ts
// preview.tsx
import { ThemeProvider } from 'theme-ui'
import type { Preview } from '@storybook/react'

const themes = {
  pp: {...},
  pk: {...},
  ff: {...},
}

const preview: Preview = {
  parameters: {
    ...
  },
  globalTypes: {
    theme: {
      name: 'Theme',
      description: 'Platform Theme',
      defaultValue: 'pp',
      toolbar: {
        icon: 'paintbrush',
        items: [
          { value: 'pp', title: 'Precious Plastic' },
          { value: 'pk', title: 'Project Kamp' },
          { value: 'ff', title: 'Fixing Fashion' },
        ],
      },
    },
  },
  decorators: [
    (Story, context) => (
      <>
        <ThemeProvider theme={themes[context.globals.theme]}>
          <Story />
        </ThemeProvider>
      </>
    ),
  ],
}

export default preview
```

![Screenshot 2023-04-15 at 13 03 13](https://user-images.githubusercontent.com/472589/232210225-8ea86b24-5857-4c33-8601-b90a273ecaf6.jpg)

**Comment by morewings** [comment]
@JulioC I created [Storybook 7 compatible theming addon](https://github.com/morewings/storybook-addon-theme-provider).

**Comment by JulioC** [comment]
Thanks for bringing this up @morewings!

Unfortunately, my use case requires real-time editing the theme properties, so I still need help from the maintainers of react-theming to get this issue fixed.

**Comment by morewings** [comment]
@JulioC I understand this. Can you give me more details on your use case? Maybe I will be able to improve my addon that way.

**Comment by JulioC** [comment]
@morewings thanks for the offer, but I believe this may be too far from your current scope...

Our design system has color tokens which can be customized for each project, based on client branding, so it's nice to change those theme properties to arbitrary values in Storybook for testing how the color will fit the components. We do it using a JSON editor in the theme selector.

**Comment by morewings** [comment]
@JulioC got it. Honestly, I use same token based theme architecture at my job. But we are editing tokens at Figma (via custom plugin). That’s why I didn’t think about adding them to Storybook. There's more than one way to skin a cat.

**Comment by usulpro** [comment]
Guys sorry for interrupting you, but didn't you consider contributing to this repo instead of creating new ones? This is an open-source project and PRs a very welcomed

**Comment by morewings** [comment]
@usulpro as far as I know apis are not compatible for 6 and 7 versions of Storybook. I haven’t seen any cross version approach yet. Didn’t mean any disrespect for your work.

**Comment by JulioC** [comment]
Still an issue

**Comment by mikematos84** [comment]
Still an issue

**Comment by JulioC** [comment]
Still an issue, but the project is abandoned anyways...

Off-topic: stale bot is so annoying! If it closes issues on abandoned projects, anyone who comes and see 0 issues will think the project is good to use. If we don't let it close, we need to keep flooding anyone watching the thread without any news. This is a deservice for everyone involved.

https://nostalebots.xyz/
